/*
 * This source file was generated by the Gradle 'init' task
 */
package progressive_testing

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(ProgressiveTestingExtension::class)
class LibraryTest {
    @TestFile("tst-file")
    fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertFalse(classUnderTest.someLibraryMethod(), "someLibraryMethod " +
                "should return 'true'")
    }
}
