/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm")
    `java-library`
    `maven-publish`
    signing
}

fun property(name: String): Any? {
    return project.findProperty(name)
}

publishing {
    repositories {
        maven {
            name = "github"
            url =
                uri(property("githubPackageRepo") as String)
            credentials {
                username = property("githubRepoUser") as String
                password = property("githubRepoPassword") as String
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
    publications {

        create<MavenPublication>("mavenKotlin") {
            from(components["java"])

            pom {
                version = "0.0.1-SNAPSHOT"
                name = "Progressive Testing"
                artifactId = "progressive_testing"
                groupId = "com.github.bitknot_project.progressive_testing"
                description =
                    "A library for running JUnit tests based on Postman " +
                            "collections. Improve the synergy between exploratory testing and " +
                            "traditional testing!"
                url = "https://github.com/bitknot-project/progressive-testing"
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://mit-license.org/"
                    }
                }

                developers {
                    developer {
                        id = "nazaratius"
                    }
                }

                scm {
                    connection =
                        "scm:git:git@github.com:bitknot-project/progressive-testing.git"
                    url =
                        "https://github.com/bitknot-project/progressive-testing#"
                }
            }
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}

dependencies {
    // this is not just a test dependency since we are building on top of
    // JUnit here.
    implementation("io.rest-assured:rest-assured:5.5.5")
    implementation("org.junit.jupiter:junit-jupiter:5.13.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.19.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
